export const actionTypes = {
    RESTART_PROGRAM: 'RESTART_PROGRAM',
    FINISH_PROGRAM: 'FINISH_PROGRAM',
    SELECT_WEEK: 'SELECT_WEEK',
    NEXT_WEEK: 'NEXT_WEEK',
    UPDATE_WEEK: 'UPDATE_WEEK',
}